# https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
github: KasparEtter
liberapay: ef1p
patreon: ef1p
custom: "https://paypal.me/KasparEtter"
