# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

title: Explained from First Principles
title_shorter: Explained from 1st Principles
description: Explained from First Principles explains complex topics from first principles.
url: https://explained-from-first-principles.com
email: contact@ef1p.com
permalink: pretty
date_format: "%e %B %Y" # http://strftime.net

google_analytics_id: UA-135908849-1
google_analytics_integrity: sha384-BCU4CQej9bXQB6TMm2c6xLfEIyUYMT/YSODyNOp1pOKbC5oaFlsLE4zz5lsMtD3t
# The integrity is determined by using https://www.srihash.org/ with
# https://www.googletagmanager.com/gtag/js?id={{ google_analytics_id }}.

twitter_handle: ExplainedFrom1P

mailchimp_action: https://explained-from-first-principles.us20.list-manage.com/subscribe/post?u=f2f847e1901ae4d294dea09da&amp;id=b2f0275e5b
mailchimp_hidden: b_f2f847e1901ae4d294dea09da_b2f0275e5b

github_repository: https://github.com/KasparEtter/ef1p

# https://github.com/jekyll/jekyll/issues/7478
theme: null

plugins:
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons"

exclude:
  - "*.json"
  - "*.scss"
  - "*.ts"
  - "*.tsx"
  - "*.txt"
  - "scss"
  - "typescript"
  - "node_modules"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "webpack.config.js"

defaults:
  - scope:
      path: ""
    values:
      layout: toc
  - scope:
      path: ""
      type: pages
    values:
      layout: article
