# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

title: Explained from First Principles
description: Explained from First Principles explains complex topics from first principles.
url: https://explained-from-first-principles.com
short_url: ef1p.com
email: contact@ef1p.com
author: Kaspar Etter
lang: en
permalink: pretty
date_format: "%e %B %Y" # http://strftime.net

github_repository: https://github.com/KasparEtter/ef1p
google_analytics_id: UA-135908849-1
mailchimp_action: https://explained-from-first-principles.us20.list-manage.com/subscribe/post?u=f2f847e1901ae4d294dea09da&amp;id=b2f0275e5b
mailchimp_hidden: b_f2f847e1901ae4d294dea09da_b2f0275e5b
twitter_handle: ExplainedFrom1P

# Hack to suppress a Jekyll issue with styles: https://github.com/jekyll/jekyll/issues/7478
theme: null

plugins:
  - jemoji

emoji:
  src: https://github.githubassets.com/images/icons

exclude:
  - "*.json"
  - "*.scss"
  - "*.ts"
  - "*.tsx"
  - "*.txt"
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - scss
  - typescript
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js

defaults:
  - scope:
      path: ""
    values:
      layout: toc
  - scope:
      path: ""
      type: pages
    values:
      layout: article
