# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

title: Explained from First Principles
description: Explained from First Principles is a technology, science, and philosophy blog for curious people who want to understand and change the world.
url: https://explained-from-first-principles.com
short_url: ef1p.com
email: contact@ef1p.com
author: Kaspar Etter
lang: en
permalink: pretty
date_format: "%e %B %Y" # http://strftime.net

google_analytics_id: UA-135908849-1
repository: KasparEtter/ef1p
twitter_handle: ExplainedFrom1P
reddit_community: https://www.reddit.com/r/ef1p/
telegram_channel: https://t.me/ExplainedFromFirstPrinciples

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  footnote_backlink: '&#8593;'

# Hack to suppress a Jekyll issue with styles: https://github.com/jekyll/jekyll/issues/7478
theme: null

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

exclude:
  - "*.json"
  - "*.ots"
  - "*.scss"
  - "*.ts"
  - "*.tsx"
  - "*.txt"
  - code
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - styles
  - vendor
  - webpack.config.js

defaults:
  - scope:
      path: pages
      type: pages
    values:
      layout: article
      permalink: /:basename/
  - scope:
      path: pages/*/tools
      type: pages
    values:
      layout: toc
