# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

title: Explained from First Principles
description: Explained from First Principles is a technology, science, and philosophy blog for curious people.
url: https://explained-from-first-principles.com
domain: explained-from-first-principles.com
short_domain: ef1p.com
email: contact@ef1p.com
author: Kaspar Etter
lang: en
permalink: pretty
date_format: '%-e %B %Y' # http://strftime.net

external_version: 2
scripts_version: 20
styles_version: 14

repository: KasparEtter/ef1p
twitter_handle: ExplainedFrom1P
twitter_handle_of_author: KasparEtter
reddit_community: https://www.reddit.com/r/ef1p/
telegram_channel: https://t.me/ExplainedFromFirstPrinciples

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  footnote_backlink: '&#8593;'

# Hack to suppress a Jekyll issue with styles: https://github.com/jekyll/jekyll/issues/7478
theme: null

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - .well-known

exclude:
  - '*.json'
  - '*.ots'
  - '*.scss'
  - '*.ts'
  - '*.tsx'
  - code
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - node_modules
  - README.md
  - styles
  - vendor
  - webpack.config.js

defaults:
  - scope:
      path: pages
      type: pages
    values:
      layout: article
      permalink: /:basename/
  - scope:
      path: pages/*/tools
      type: pages
    values:
      layout: toc
