# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

title: Explained from First Principles
description: Explained from First Principles explains complex topics from first principles.
url: https://explained-from-first-principles.com
short_url: ef1p.com
email: contact@ef1p.com
author: Kaspar Etter
lang: en
permalink: pretty
date_format: "%e %B %Y" # http://strftime.net

google_analytics_id: UA-135908849-1
telegram_channel: https://t.me/ExplainedFromFirstPrinciples
twitter_handle: ExplainedFrom1P

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  footnote_backlink: '&#8593;'

# Hack to suppress a Jekyll issue with styles: https://github.com/jekyll/jekyll/issues/7478
theme: null

exclude:
  - "*.json"
  - "*.scss"
  - "*.ts"
  - "*.tsx"
  - "*.txt"
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - scss
  - typescript
  - vendor
  - webpack.config.js

defaults:
  - scope:
      path: ""
    values:
      layout: toc
  - scope:
      path: ""
      type: pages
    values:
      layout: article
